nelmio_api_doc:
    documentation:
        info:
            title: Job postions app
            description: This is an awesome app!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc|doc.json$)
